jobs:
- name: bootstrap-tooling
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
  - task: create-update-tooling
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
      STACK_NAME: tooling
      TEMPLATE_SUBDIR: terraform/stacks/tooling
      S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_DEFAULT_REGION: {{aws_default_region}}
      TF_VAR_az1: {{aws_az1}}
      TF_VAR_az2: {{aws_az2}}
      TF_VAR_aws_partition: {{aws_partition}}
      TF_VAR_aws_default_region: {{aws_default_region}}
      TF_VAR_account_id: {{aws_account_id}}
      TF_VAR_rds_password: {{tooling_rds_password}}
      TF_VAR_concourse_prod_rds_password: {{concourse_prod_rds_password}}
      TF_VAR_concourse_prod_cidr: {{concourse_prod_cidr}}
      TF_VAR_concourse_staging_rds_password: {{concourse_staging_rds_password}}
      TF_VAR_concourse_staging_cidr: {{concourse_staging_cidr}}
      TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
      TF_VAR_staging_private_bucket: {{staging_private_bucket}}
      TF_VAR_prod_private_bucket: {{prod_private_bucket}}
      TF_VAR_bosh_releases_bucket: {{bosh_releases_bucket}}
      TF_VAR_bosh_stemcells_bucket: {{bosh_stemcells_bucket}}
      TF_VAR_vpc_cidr: {{tooling_vpc_cidr}}
      TF_VAR_public_cidr_1: {{tooling_public_cidr_1}}
      TF_VAR_public_cidr_2: {{tooling_public_cidr_2}}
      TF_VAR_private_cidr_1: {{tooling_private_cidr_1}}
      TF_VAR_private_cidr_2: {{tooling_private_cidr_2}}
      TF_VAR_rds_private_cidr_1: {{tooling_rds_private_cidr_1}}
      TF_VAR_rds_private_cidr_2: {{tooling_rds_private_cidr_2}}
      TF_VAR_restricted_ingress_web_cidrs: {{tooling_restricted_ingress_web_cidrs}}
      TF_VAR_nat_gateway_ami: {{nat_gateway_ami}}
      TF_VAR_concourse_prod_elb_cert_name: {{concourse_prod_elb_cert_name}}
      TF_VAR_concourse_staging_elb_cert_name: {{concourse_staging_elb_cert_name}}
      TF_VAR_nessus_elb_cert_name: {{nessus_elb_cert_name}}
  - task: init-bosh-db
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/psql
      inputs:
        - name: cg-provision-repo
        - name: terraform-state
      params:
        BOSH_DB_PASSWORD: {{tooling_rds_password}}
        STATE_FILE_PATH: terraform-state/terraform.tfstate
      run:
        path: sh
        args:
        - -e
        - -c
        - cg-provision-repo/ci/scripts/update-bosh-db.sh

- name: bootstrap-staging
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
  - task: create-update-staging
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
      STACK_NAME: staging
      TEMPLATE_SUBDIR: terraform/stacks/staging
      S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_DEFAULT_REGION: {{aws_default_region}}
      TF_VAR_az1: {{aws_az1}}
      TF_VAR_az2: {{aws_az2}}
      TF_VAR_aws_partition: {{aws_partition}}
      TF_VAR_account_id: {{aws_account_id}}
      TF_VAR_rds_password: {{staging_rds_password}}
      TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
      TF_VAR_vpc_cidr: {{staging_vpc_cidr}}
      TF_VAR_public_cidr_1: {{staging_public_cidr_1}}
      TF_VAR_public_cidr_2: {{staging_public_cidr_2}}
      TF_VAR_private_cidr_1: {{staging_private_cidr_1}}
      TF_VAR_private_cidr_2: {{staging_private_cidr_2}}
      TF_VAR_services_cidr_1: {{staging_services_cidr_1}}
      TF_VAR_services_cidr_2: {{staging_services_cidr_2}}
      TF_VAR_rds_private_cidr_1: {{staging_rds_private_cidr_1}}
      TF_VAR_rds_private_cidr_2: {{staging_rds_private_cidr_2}}
      TF_VAR_cf_rds_password: {{staging_cf_rds_password}}
      TF_VAR_restricted_ingress_web_cidrs: {{staging_restricted_ingress_web_cidrs}}
      TF_VAR_nat_gateway_ami: {{nat_gateway_ami}}
      TF_VAR_main_cert_name: {{main_cert_name}}
      TF_VAR_apps_cert_name: {{apps_cert_name}}
      TF_VAR_monitoring_elb_cert_name: {{monitoring_elb_cert_name}}
  - task: init-bosh-db
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/psql
      inputs:
        - name: cg-provision-repo
        - name: terraform-state
      params:
        BOSH_DB_PASSWORD: {{staging_rds_password}}
        STATE_FILE_PATH: terraform-state/terraform.tfstate
      run:
        path: sh
        args:
        - -e
        - -c
        - cg-provision-repo/ci/scripts/update-bosh-db.sh
  - task: init-cf-db
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/psql
      inputs:
        - name: cg-provision-repo
        - name: terraform-state
      params:
        CF_DB_PASSWORD: {{staging_cf_rds_password}}
        STATE_FILE_PATH: terraform-state/terraform.tfstate
      run:
        path: sh
        args:
        - -e
        - -c
        - cg-provision-repo/ci/scripts/update-cf-db.sh

- name: bootstrap-production
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
  - task: create-update-production
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
      STACK_NAME: production
      TEMPLATE_SUBDIR: terraform/stacks/production
      S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_DEFAULT_REGION: {{aws_default_region}}
      TF_VAR_az1: {{aws_az1}}
      TF_VAR_az2: {{aws_az2}}
      TF_VAR_aws_partition: {{aws_partition}}
      TF_VAR_account_id: {{aws_account_id}}
      TF_VAR_rds_password: {{production_rds_password}}
      TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
      TF_VAR_vpc_cidr: {{production_vpc_cidr}}
      TF_VAR_public_cidr_1: {{production_public_cidr_1}}
      TF_VAR_public_cidr_2: {{production_public_cidr_2}}
      TF_VAR_private_cidr_1: {{production_private_cidr_1}}
      TF_VAR_private_cidr_2: {{production_private_cidr_2}}
      TF_VAR_services_cidr_1: {{production_services_cidr_1}}
      TF_VAR_services_cidr_2: {{production_services_cidr_2}}
      TF_VAR_rds_private_cidr_1: {{production_rds_private_cidr_1}}
      TF_VAR_rds_private_cidr_2: {{production_rds_private_cidr_2}}
      TF_VAR_cf_rds_password: {{production_cf_rds_password}}
      TF_VAR_restricted_ingress_web_cidrs: {{production_restricted_ingress_web_cidrs}}
      TF_VAR_nat_gateway_ami: {{nat_gateway_ami}}
      TF_VAR_main_cert_name: {{main_cert_name}}
      TF_VAR_apps_cert_name: {{apps_cert_name}}
      TF_VAR_monitoring_elb_cert_name: {{monitoring_elb_cert_name}}
  - task: init-bosh-db
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/psql
      inputs:
        - name: cg-provision-repo
        - name: terraform-state
      params:
        BOSH_DB_PASSWORD: {{production_rds_password}}
        STATE_FILE_PATH: terraform-state/terraform.tfstate
      run:
        path: sh
        args:
        - -e
        - -c
        - cg-provision-repo/ci/scripts/update-bosh-db.sh
  - task: init-cf-db
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/psql
      inputs:
        - name: cg-provision-repo
        - name: terraform-state
      params:
        CF_DB_PASSWORD: {{production_cf_rds_password}}
        STATE_FILE_PATH: terraform-state/terraform.tfstate
      run:
        path: sh
        args:
        - -e
        - -c
        - cg-provision-repo/ci/scripts/update-cf-db.sh

- name: teardown-tooling
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
#      passed: [teardown-staging, teardown-production]
  - task: destroy
    file: pipeline-tasks/terraform-destroy.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
     STACK_NAME: tooling
     TEMPLATE_SUBDIR: terraform/stacks/tooling
     S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
     AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
     AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
     AWS_DEFAULT_REGION: {{aws_default_region}}
     TF_VAR_az1: {{aws_az1}}
     TF_VAR_az2: {{aws_az2}}
     TF_VAR_aws_partition: {{aws_partition}}
     TF_VAR_aws_default_region: {{aws_default_region}}
     TF_VAR_account_id: {{aws_account_id}}
     TF_VAR_rds_password: {{tooling_rds_password}}
     TF_VAR_concourse_prod_rds_password: {{concourse_prod_rds_password}}
     TF_VAR_concourse_prod_cidr: {{concourse_prod_cidr}}
     TF_VAR_concourse_staging_rds_password: {{concourse_staging_rds_password}}
     TF_VAR_concourse_staging_cidr: {{concourse_staging_cidr}}
     TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
     TF_VAR_staging_private_bucket: {{staging_private_bucket}}
     TF_VAR_prod_private_bucket: {{prod_private_bucket}}
     TF_VAR_bosh_releases_bucket: {{bosh_releases_bucket}}
     TF_VAR_bosh_stemcells_bucket: {{bosh_stemcells_bucket}}
     TF_VAR_vpc_cidr: {{tooling_vpc_cidr}}
     TF_VAR_public_cidr_1: {{tooling_public_cidr_1}}
     TF_VAR_public_cidr_2: {{tooling_public_cidr_2}}
     TF_VAR_private_cidr_1: {{tooling_private_cidr_1}}
     TF_VAR_private_cidr_2: {{tooling_private_cidr_2}}
     TF_VAR_rds_private_cidr_1: {{tooling_rds_private_cidr_1}}
     TF_VAR_rds_private_cidr_2: {{tooling_rds_private_cidr_2}}
     TF_VAR_restricted_ingress_web_cidrs: {{tooling_restricted_ingress_web_cidrs}}
     TF_VAR_nat_gateway_ami: {{nat_gateway_ami}}
     TF_VAR_concourse_prod_elb_cert_name: {{concourse_prod_elb_cert_name}}
     TF_VAR_concourse_staging_elb_cert_name: {{concourse_staging_elb_cert_name}}
     TF_VAR_nessus_elb_cert_name: {{nessus_elb_cert_name}}

- name: teardown-staging
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
#      passed: [bootstrap-staging]
  - task: destroy
    file: pipeline-tasks/terraform-destroy.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
     STACK_NAME: staging
     TEMPLATE_SUBDIR: terraform/stacks/staging
     S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
     AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
     AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
     AWS_DEFAULT_REGION: {{aws_default_region}}
     TF_VAR_az1: {{aws_az1}}
     TF_VAR_az2: {{aws_az2}}
     TF_VAR_aws_partition: {{aws_partition}}
     TF_VAR_account_id: {{aws_account_id}}
     TF_VAR_rds_password: {{staging_rds_password}}
     TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
     TF_VAR_vpc_cidr: {{staging_vpc_cidr}}
     TF_VAR_public_cidr_1: {{staging_public_cidr_1}}
     TF_VAR_public_cidr_2: {{staging_public_cidr_2}}
     TF_VAR_private_cidr_1: {{staging_private_cidr_1}}
     TF_VAR_private_cidr_2: {{staging_private_cidr_2}}
     TF_VAR_services_cidr_1: {{staging_services_cidr_1}}
     TF_VAR_services_cidr_2: {{staging_services_cidr_2}}
     TF_VAR_rds_private_cidr_1: {{staging_rds_private_cidr_1}}
     TF_VAR_rds_private_cidr_2: {{staging_rds_private_cidr_2}}
     TF_VAR_cf_rds_password: {{staging_cf_rds_password}}
     TF_VAR_restricted_ingress_web_cidrs: {{staging_restricted_ingress_web_cidrs}}
     TF_VAR_nat_gateway_ami: {{nat_gateway_ami}}
     TF_VAR_main_cert_name: {{main_cert_name}}
     TF_VAR_apps_cert_name: {{apps_cert_name}}
     TF_VAR_monitoring_elb_cert_name: {{monitoring_elb_cert_name}}

- name: teardown-production
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      passed: [bootstrap-production]
  - task: destroy
    file: pipeline-tasks/terraform-destroy.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
     STACK_NAME: production
     TEMPLATE_SUBDIR: terraform/stacks/production
     S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
     AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
     AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
     AWS_DEFAULT_REGION: {{aws_default_region}}
     TF_VAR_az1: {{aws_az1}}
     TF_VAR_az2: {{aws_az2}}
     TF_VAR_aws_partition: {{aws_partition}}
     TF_VAR_account_id: {{aws_account_id}}
     TF_VAR_rds_password: {{production_rds_password}}
     TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
     TF_VAR_vpc_cidr: {{production_vpc_cidr}}
     TF_VAR_public_cidr_1: {{production_public_cidr_1}}
     TF_VAR_public_cidr_2: {{production_public_cidr_2}}
     TF_VAR_private_cidr_1: {{production_private_cidr_1}}
     TF_VAR_private_cidr_2: {{production_private_cidr_2}}
     TF_VAR_services_cidr_1: {{production_services_cidr_1}}
     TF_VAR_services_cidr_2: {{production_services_cidr_2}}
     TF_VAR_rds_private_cidr_1: {{production_rds_private_cidr_1}}
     TF_VAR_rds_private_cidr_2: {{production_rds_private_cidr_2}}
     TF_VAR_cf_rds_password: {{production_cf_rds_password}}
     TF_VAR_restricted_ingress_web_cidrs: {{production_restricted_ingress_web_cidrs}}
     TF_VAR_nat_gateway_ami: {{nat_gateway_ami}}
     TF_VAR_main_cert_name: {{main_cert_name}}
     TF_VAR_apps_cert_name: {{apps_cert_name}}
     TF_VAR_monitoring_elb_cert_name: {{monitoring_elb_cert_name}}

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/18F/cg-pipeline-tasks.git
    branch: master

- name: cg-provision-repo
  type: git
  source:
    uri: https://github.com/s-matyukevich/cg-provision.git
    branch: test
